"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
from setuptools import setup

APP = ['aacircuit.py']
# DATA_FILES = ['application/style.css', 'application/components/component_de.json']
DATA_FILES = [
 ('application', ['application/style.css']),
 ('components', ['application/component_de.json']),
 ('locale/de/LC_MESSAGES', ['locale/de/LC_MESSAGES/aacircuit.mo']),
 ('locale/de/LC_MESSAGES', ['locale/de/LC_MESSAGES/aacircuit.po']),
 ('locale/nl/LC_MESSAGES', ['locale/nl/LC_MESSAGES/aacircuit.mo']),
 ('locale/nl/LC_MESSAGES', ['locale/nl/LC_MESSAGES/aacircuit.po'])
]
OPTIONS = {}

buttons = 'application/buttons'
for f in os.listdir(buttons):
    # print("btn:", f)
    df = ('application/buttons', ['application/buttons/' + f])
    DATA_FILES.append(df)

setup(
    app=APP,
    package=('application'),
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
